rust-embedded-community/ssd1306

examples/blinky.rs
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/pixelsquare.rs
examples/text_i2c.rs
src/command.rs
src/interface/i2c.rs
src/interface/mod.rs
src/interface/spi.rs
src/lib.rs

Quick fix-up for #9 
* hal::blocking::spi::Transfer wasn't necessary on the SPI implementation, removed it.
* Added an Error associated type to the DisplayInterface trait.
* passed along errors where necessary rather than silencing them.

Error handling

---

src/interface/i2c.rs

Gone from 1025 byte buffer down to 17, although sending data to the display is marginally less efficient. Should be fine.
@scowcron This is from your `rust-ssd1306` crate. Any thoughts?
Fixes #6.

Use much less memory in I2C interface

---

.cargo/config
src/builder.rs
src/displaysize.rs
src/interface/i2c.rs
src/interface/mod.rs
src/interface/spi.rs
src/lib.rs

Start to #8. This *DOES NOT* close that issue, the docs need to be more thoroughly fleshed out, but it allows us to enable the lint going forward and enforce good (developer) behavior.

Add outline to docs and deny them in the future

---

src/builder.rs
src/interface/i2c.rs

Section 8.1.5) a) in the datasheet states that the display address can be 0x3C or 0x3D, chosen with the D/C pin.
It can now be configured using the `.with_i2c_addr()` method on the `Builder`. Example:
```rust
let mut disp = Builder::new()
.with_size(DisplaySize::Display128x32)
.with_i2c_addr(0x3d)
.connect_i2c(i2c);
```
Closes #12.
@scowcron This is where the builder pattern starts making sense to me; it feels more Rustic to chain a bunch of calls together to configure the object. Feels a bit like chaining iterator methods.

Un-hard-code I2C address

---

src/lib.rs

Closeses #19 
@scowcron I can't decide if this should be a noop or return a `Result`. The latter feels more Rustic, but what's the user going to do with it? They should be checking the display dimensions, not whether a pixel was out of bounds or not. Thoughts?

Add guard around out of bounds pixel set

---

examples/rotation_i2c.rs
src/builder.rs
src/displayrotation.rs
src/lib.rs

Adds 0, 90, 180 and 270 degree rotations to the display. Usable like so:
```rust
let mut disp = Builder::new()
.with_rotation(DisplayRotation::Rotate90)
.connect_i2c(i2c);
```
Also adds the `get_dimensions()` method so consumers of this driver can position stuff relative to the display size.

Display rotation

---

Cargo.toml

As raised by @therealprof and @chocol4te in #30, it makes sense to have
these features enabled by default, but disable-able if someone _really_
needs to. The compiler will optimise it all out anyway.

Turn graphics feature on by default

---

examples/blinky_i2c.rs

This addresses #33 with a hopefully helpful example that uses RTFM's `app!` macro.
Closes #33

Add I2C version of blinky example

---

Cargo.toml
examples/image_i2c.rs
examples/rotation_i2c.rs
examples/text_i2c.rs

This should've been done in the first place really. By locking the dependency at a hash, breaking changes shouldn't leak to this crate. Also fixes all the examples.
Closes jamwaffles/embedded-graphics#9

Lock embedded_graphics to commit hash

---

src/mode/graphics.rs
src/properties.rs

Moved more general code to properties.rs for deduplication

---

examples/blinky.rs
examples/blinky_i2c.rs
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/image_i2c.rs
examples/pixelsquare.rs
examples/rotation_i2c.rs
examples/text_i2c.rs
src/builder.rs
src/mode/displaymode.rs
src/mode/graphics.rs
src/mode/mod.rs
src/mode/raw.rs

Implement DisplayMode and DisplayTrait for better mode handling

---

src/interface/i2c.rs

Nicen up I2C buffer assembly a bit, also yields smaller binaries

---

src/mode/graphics.rs

@therealprof None of my stuff was working. I thought I was going insane, turns out it was just a typo in argument order 😂. TerminalMode [does it right](https://github.com/jamwaffles/ssd1306/blob/fix-graphics-addressing/src/mode/terminal.rs#L162).

Fix typo in set_draw_area()

---

Cargo.toml
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/image_i2c.rs
examples/rotation_i2c.rs
examples/terminal_i2c.rs
examples/text_i2c.rs

Embedded graphics got a prelude in jamwaffles/embedded-graphics@c5b8eb36425b172cab7b3d33b045b1ef8f71c3bd. 
This allows us to fix a lot of the import noise for using embedded_graphics. I've also removed the embedded_graphics dependency from your terminal demo @therealprof.
Some rustfmt stuff snuck in as well, mostly item ordering.

Update to embedded_graphics with prelude

---

.cargo/config
.travis.yml
Cargo.toml
examples/blinky.rs
examples/blinky_i2c.rs
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/image_i2c.rs
examples/pixelsquare.rs
examples/rotation_i2c.rs
examples/terminal_i2c.rs
examples/text_i2c.rs

[We can now use LLD to link Cortex-M programs!](https://users.rust-lang.org/t/cortex-m-rt-v0-4-0-now-you-can-link-arm-cortex-m-programs-using-lld/16751). This change moves over to using lld in `.cargo/config`. I haven't tested this with any hardware yet so don't merge just yet.

Use LLD to link programs

---

src/builder.rs
src/displayrotation.rs

Replaces #61, closes #28
Rotation in terminalmode requires [adding unwanted complexity](https://github.com/jamwaffles/ssd1306/pull/61/commits/c1c2a39e30ff6e10d79a335ce18027a4e63c0db2),
which isn't good for TerminalMode which should stay pretty lightweight.
This PR adds some docs telling the user that particular rotations don't
work for TerminalMode.
I'm on the fence about making `set_rotation()` return an `Err()` if the
user tries to set 90/270º rotations. Thoughts?

90/270º TerminalMode rotation docs

---

Cargo.toml
README.md
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/image_i2c.rs
examples/rotation_i2c.rs
examples/text_i2c.rs
src/lib.rs
src/mode/graphics.rs

The API for handling Pixels changed, so this change is mostly about updating that. Note that I don't have the hardware to test the examples, so I mostly just checked as far as I could with 'cargo check'. I was able to test the library itself on a Raspberry Pi though.
I'm also not sure how Rust libraries handle changing the major version of libraries they depend on. I guess this would be considered a breaking change?

Support embedded-graphics 0.3.0

---

src/mode/graphics.rs

`set_pixel` already does nothing if pixel memory index is larger than buffer size.
However, when pixel overflows by x, it simply overflows into the next row (y coordinate) instead of being ignored.
This commit fixes it, and causes it to be ignored.

Don't wrap around when x >= width

---

Cargo.toml
examples/graphics.rs
examples/pixelsquare.rs
src/builder.rs
src/command.rs
src/interface/i2c.rs
src/interface/mod.rs
src/interface/spi.rs
src/lib.rs
src/mode/graphics.rs
src/mode/terminal.rs
src/properties.rs

Very similarly to https://github.com/jamwaffles/sh1106/pull/8, I added an error `enum` with two types: a communication error type and a pin error type which allows users to handle I2C or SPI communication errors as well as SPI pin setting errors.
I had to make `reset` fallible, though. User code will then get an unused Result warning.
No other changes are required in user code if the results were simply unwrapped.

Use the embedded-hal::digital::v2::OutputPin

---

src/mode/graphics.rs
src/mode/terminal.rs
src/properties.rs

Implements #84 . Tested using [Adafruit OLED Featherwing](https://www.adafruit.com/product/2900). Display has no issues accepting commands while switched off so I don't believe there is a need to implement any interlocks or new state.
Closes #84

Implement switching display power

---

.travis.yml
build.sh
src/builder.rs
src/interface/mod.rs
src/lib.rs
src/mode/graphics.rs
src/mode/terminal.rs
src/properties.rs
src/test_helpers.rs

* Clarify builder docs as per #87 
* Test code examples in CI (also #87)
* Check doc links using `linkchecker` in CI
Closes #87

Clarify builder docs, test doc examples in CI

---

src/command.rs
src/mode/terminal.rs
src/properties.rs

This supersedes #79 by tracking the full vertical and horizontal position ourselves within `TerminalMode`, and implementing line-wrapping manually. This means we can use the `Page` addressing mode, so we can write characters to arbitrary points on the screen, while still remaining bufferless. As a bonus, we can handle `\r` properly.
There may be places that this could be cleaned up—I especially don't like the potential confusion between "pages" and "rows" and the magic `* 8` which needs to be in place (it probably needs a few wrapper types). It does work though—tested manually over I2C on a cheap AliExpress SSD1306 board.
Closes #78

Terminal mode cursor

---

README.md
examples/bmp_i2c.rs
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/image_i2c.rs
examples/pixelsquare.rs
examples/rotation_i2c.rs
examples/text_i2c.rs
src/interface/i2c.rs
src/interface/mod.rs
src/interface/spi.rs
src/lib.rs
src/mode/graphics.rs
src/properties.rs
src/test_helpers.rs

This increases the performance of the I2C interface and possibly the SPI interface as well, but I don't have a SPI-based SSD1306 for verification. The main idea comes from the fact that the SSD1306 has support for writing to a subset of the display memory buffer as if it were contiguous. This means that if you only have a small window within the display to update, you don't have to update the entire display.
This is achieved by keeping track of the locations of the pixels that have changed since the last call to flush or reset. The only values we need to track are the max and min values for the x and y coordinates of each pixel. Once a new call to flush happens (fast_flush in this pull request), the elements of the display buffer on the micro-controller that are within the minimum …

Improve I2C Flush (Update) Speed

---

CHANGELOG.md
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs

- Use the new _Triangle_ primitive provided by _embedded_graphics_ 0.6.0-alpha.2 in the graphics demos
- Also added back the "screen outline" rectangle as seen in the original SSD1306 driver announcement blog post
- Added connection info for the *pill/display boards in the comments of examples/graphics_i2c_128x32.rs
- Tweaked the positions of the shapes a bit to "center" them
**NOTE**: I don't have a 3-wire SPI OLED board to test on, I only have a 4-wire SPI board available to me at the moment, so I was only able to test the refactored I2C demos.  The SPI OLED example (`graphics.rs`) compiles, I just can't test it 😕.  I tried grounding the CS line, but I wasn't able to get my 4-wire board to work.
If you're interested, I'd like to also add a blinkenled to the graphics examples, that way …

examples/graphics*.rs: use new 'Triangle' primitive

---

CHANGELOG.md
examples/graphics_i2c_72x40.rs
src/displaysize.rs
src/mode/graphics.rs
src/mode/terminal.rs
src/properties.rs

Adds support for the 72x40px variant of the SSD1306. I believe this is also sometimes advertised as a 70x40px display. [This Reddit thread](https://www.reddit.com/r/arduino/comments/bup1kf/anyone_got_one_of_these_little_beauties_working/) was handy in figuring out a display offset of `(28, 0)` pixels. This is handled by the driver, so no user code needs to change.

Add support for 72x40px SSD1306 modules

---

CHANGELOG.md
src/mode/graphics.rs

Removes the `unwraps()` in `DrawTarget`. Reduces `.text` section when running `cargo bloat --example graphics` from 54.4KiB to 54.0KiB.
In release mode, that goes from 13.6KiB to 13.2KiB.

Remove unwraps, replace with `as` coercion

---

CHANGELOG.md
src/interface/i2c.rs
src/interface/spi.rs
src/mode/graphics.rs

Switches some `for` loops for iterators to speed up sends (and hopefully reduce code size) by eliding bounds checks.

Use iterators in interface send methods

---

CHANGELOG.md
Cargo.toml
examples/noise_i2c.rs

This is the result of an email discussion with @nebelgrau77 who is asking for assistance sending raw bytes to the display, without using `GraphicsMode`, etc. The example emulates an old TV with a white noise effect using random crap from the `rand` crate in no-std mode.

Add raw random noise example

---

CHANGELOG.md
src/displaysize.rs
src/mode/terminal.rs
src/properties.rs

I've got [a display that seems to use the SSD1306](https://www.aliexpress.com/item/32782787258.html). As far as I know, all that has to be added is a new DisplaySize enum and the corresponding match cases.
The HAL library for the MCU I have access to (STM32F303) currently has a bug that makes the SPI transfer LSBit-first, so I unfortunately can't submit an example that works out of the box. Would it be better to add an example that I can't test or to leave it to someone else?

Add support for 64x48px SSD1306 modules

---

CHANGELOG.md
examples/noise_i2c.rs
src/mode/displaymode.rs
src/mode/graphics.rs
src/mode/terminal.rs
src/properties.rs

Hi!
I have a device that can physically cut supply to the display. In order to do that, I must ensure that the pins are floating or low, so I must be able to deconstruct the display driver to reclaim the pins.
This is a no-brainer implementation of the above functionality. Any feedback is welcome, if there is a better place to do this, or if the feature is already there but I'm blind. I've also bumped the display-interface dependencies because I rely on those as well.
Other todo items will be checked once this PR can get a green light.
Thank you :)

Allow reclaiming display pins

---

CHANGELOG.md
src/mode/displaymode.rs
src/mode/graphics.rs
src/mode/terminal.rs

The functionality is common, so the implementation can be as well.
Just a bit of cleanup. Should be backwards compatible since the trait is in the prelude. I don't think there should be a changelog entry for this one.

Move reset to DisplayModeTrait

---

CHANGELOG.md
Cargo.toml
examples/graphics_i2c_128x32.rs
examples/graphics_i2c_72x40.rs
src/builder.rs
src/command.rs
src/displaysize.rs
src/lib.rs
src/mode/displaymode.rs
src/mode/graphics.rs
src/mode/terminal.rs
src/prelude.rs
src/properties.rs

This is just a rough draft of how I imagine type-level display sizes. This has several added benefits:
- allows the user to specify display sizes
- ~can be extended via GenericArray to support flexible display buffer size~ accidentally implemented
- hopefully allows generating much nicer machine code
The downside is the amount of code changed and the API it broke...
Closes #20 
Closes #122

Type-level display size

---

src/builder.rs

The type system fails to auto-coerce it to the right type and it's also
not necessary since we know quite well what the function will return.
Closes #131

Explicitly return the type instead of returning an impl trait

---

CHANGELOG.md
src/builder.rs
src/displayrotation.rs
src/mode/terminal.rs

~I had a go with #85 and failed miserably. But while doing so, I discovered the driver crashes with 90° rotation. This PR fixes that crash, but does nothing to fix the rotation issue.~
The issue is, properties.get_dimension flips width and height but set_draw_area expects them in the original order. I think for clearing it doesn't matter which direction we go, so I'm using the original physical size instead.
This is a performance hit, because every cursor move sends several display commands, but all the rotation values are rendered correctly.

Fix terminal mode

---

Cargo.toml

Remove `memory.x`, `build.rs` and various binary files from the published crate. A side effect is that size of the bundle is decreased down to 35 KB from 2.4 MB.
Closes #143

Exclude various files from the cargo package

---

CHANGELOG.md
src/displaysize.rs
src/mode/graphics.rs

All display sizes, except for the 96x16 are centered, meaning OFFSETX is same for both 0 and 180 rotations. The 96x16 is an exception to this, where it's OFFSETX is 0.
This PR changes `flush()` so it doesn't assume a symmetrical display. I also added the option to specify different driver sizes, but I'm pretty sure the only reason for that in this driver is to avoid a magic number (128) in the code.
Also 72x40 rotation was broken due to swapped X/Y offsets.
Tested on 128x32, 72x40 and 96x16 displays.
Closes #138

Fix display rotation for different screen sizes

---

CHANGELOG.md
Cargo.toml
src/mode/buffered_graphics.rs

The new core crate is designed for driver use, hence this PR. Also some minor cleanup in `Cargo.toml`.

Use embedded-graphics-core instead of embedded-graphics

---

CHANGELOG.md
Cargo.toml
src/mode/buffered_graphics.rs
src/size.rs

`generic-array` really inhibits compiler optimizations, especially when creating one. And since we have big buffers using `GenericArray`, it does make a really big difference. I was having trouble with stack overflows on my 4kB RAM chip, so I went to measure RAM usage, `do_thing` is a function that creates a display driver and prints an simple image to the display:
Current release:
```
0x08000d59      4208    f0_embassy::do_thing::h6248afff2c8c745f
```
With this PR:
```
0x08000d59      1192    f0_embassy::do_thing::h8f7d94a24b293d88
```

Get rid of generic-array

---

CHANGELOG.md
src/size.rs

Adding a predefined configuration for 64x32 displays, commonly marketed as "0.49" OLED display" like [this panel](https://www.buydisplay.com/0-49-inch-oled-display-module-64x32-pixel-ssd1306-spi-i2c-white-on-black) or [this module](https://www.buydisplay.com/i2c-white-0-49-inch-oled-display-module-64x32-arduino-raspberry-pi).

Add DisplaySize configuration for 64x32 displays

---

CHANGELOG.md
src/lib.rs

Reset can't return a comm error, so let's make it Infallible. Also, there's no need for a third generic type.

Remove a generic param, signify no comm error during reset

---

.circleci/config.yml
CHANGELOG.md
Cargo.toml
examples/bmp_i2c.rs
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/graphics_i2c_72x40.rs
examples/image_i2c.rs
examples/noise_i2c.rs
examples/pixelsquare.rs
examples/rotation_i2c.rs
examples/rtic_brightness.rs
examples/rtic_dvd.rs
examples/terminal_i2c.rs
examples/text_i2c.rs

Update embedded-graphics and modernize examples.

Bump e-g core

---

CHANGELOG.md
src/lib.rs

Add `Ssd1306::set_invert()` to invert the screen drawing.

Add display invertion

---

CHANGELOG.md
src/mode/buffered_graphics.rs

Currently `clear()` fills the buffer with `0x01` bytes, which represent
7 dark pixels and 1 bright pixel. We want all pixels bright. This PR fixes it by filling buffer with 0xff.

Fix `BufferedGraphicsMode::clear()` so that it fills all pixels

---

CHANGELOG.md
src/lib.rs

Just a method that consumes the Ssd1306 and returns the contained interface.

Add method to release the contained interface

---

Cargo.toml

With the configuration currently in master
> cargo build --all-features --release
Will use the latest `maybe-async-cfg` which is `0.2.5`. This causes compilation errors.
This change pins the version to `=0.2.4` rather than attempting to upgrade to the latest version. I'll leave that as an excersise to someone with more experience with maybe-async-cfg.
--
Details about the errors encountered:
When 0.2.5 is selected we see the following compilation errors and many other similar ones:
```bash
error[E0277]: `Result<(), DisplayError>` is not a future
--> src/size.rs:184:56
|
184 |         Command::ComPinConfig(true, false).send(iface).await
|                                                       -^^^^^
|                                                       ||
| …
```

Pin maybe-async-cfg to version 0.2.4 due to breaking changes in latest.

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml

- Update dependencies for  `embassy-executor` to 0.7.0
- Remove `embassy-executor` feature  "integrated-timer". See https://github.com/embassy-rs/embassy/blob/main/embassy-executor/CHANGELOG.md
- Switch `embassy-executor` from git to crates.io
- Update dependencies for `embassy-stm32`  to 0.2.0
- Switch `embassy-stm32` from git to crates.io
- Update dependencies for `embassy-time` to 0.4.0
- Switch `embassy-time` from git to crates.io
- Update dependencies for `tinybmp` to 0.5.0
- Update root-toolchain  to  1.84  for  github workflow in ci.yml

- Update dependencies for  `embassy-executor` to 0.7.0

---

CHANGELOG.md
Cargo.toml
examples/bmp_i2c.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/graphics_i2c_72x40.rs
examples/image_i2c.rs
examples/noise_i2c.rs
examples/rotation_i2c.rs
examples/terminal_i2c.rs
examples/text_i2c.rs
src/i2c_interface.rs
src/mode/terminal.rs

- If feature `async`is enabled, the embedded_hal_async::i2c::I2  is used instead of embedded_hal::i2c::I2c  so I2c can shared
- Update examples
- Switch iterator in `write_str` in mode/terminal.rs  from last() to next_back (see https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last)
- parenthese for expression in in mode/terminal.rs (see https://rust-lang.github.io/rust-clippy/master/index.html#precedence) in mode/terminal.rs

- Update dependcies for `embedded-hal-bus` to 0.3.0

---

CHANGELOG.md
Cargo.toml

As maybe-async-cfg crate docs suggested
`maybe_async_cfg` crate suggested to add resolver v2 directive. For me it fixes compilation issues.
> RECOMMENDATION: Enable resolver ver2 in your crate, which is introduced in Rust 1.51. If not, two crates in dependency with conflict version (one async and another blocking) can fail compilation.

Enable resolver ver2

---

src/prelude.rs

I noticed that 64x32 was missing in prelude

Add DisplaySize64x32 to prelude

---

src/i2c_interface.rs

Unharmful typo fix in i2c interface documentation, 0x3C is the default address.

Fix typo in i2c documentation
