.cargo/config

Removed runner and added only supported example target as default

---

examples/image_i2c.rs

Silence warnings in examples

---

src/builder.rs
src/lib.rs
src/mode/graphics.rs
src/mode/raw.rs
src/properties.rs

Refactored some code into DisplayProperties to simplify mode handling

---

.travis.yml
README.md
build.sh

We don't have much in the way of docs at the moment, but this is a start to getting them out there.
Ref #8 but this still doesn't close it.

Add doc upload to Travis build

---

src/interface/i2c.rs

Fixed rebase SNAFU with duplicated code and provided simpler impl

---

src/properties.rs

Fixed bug recently introduced in set_draw_area()

---

src/command.rs
src/interface/i2c.rs
src/interface/mod.rs
src/interface/spi.rs

This allows us to send multiple commands at once both speeding up the
communication by quite a bit and cutting down the program size
considerably. Fixes #42.

Changed send_command() -> send_commands() to batch commands

---

examples/blinky.rs
examples/blinky_i2c.rs
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/image_i2c.rs
examples/pixelsquare.rs
examples/rotation_i2c.rs
examples/terminal_i2c.rs
examples/text_i2c.rs
src/lib.rs
src/prelude.rs

Add prelude

---

Cargo.toml

Release metadata

---

Cargo.toml

Pin stm32f103xx-hal version. Fixes #66.

---

Cargo.toml
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/text_i2c.rs

Now has transforms and some basic styling

Embedded graphics upgrade to 0.4.0

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Copypasta'd from jamwaffles/embedded-graphics and modified to suit this repo.

Add PR/issue templates

---

.github/FUNDING.yml
CHANGELOG.md
Cargo.toml
README.md
build.rs
examples/bmp_i2c.rs
examples/graphics.rs
examples/graphics_i2c.rs
examples/graphics_i2c_128x32.rs
examples/image_i2c.rs
examples/pixelsquare.rs
examples/rotation_i2c.rs
examples/terminal_i2c.rs
examples/text_i2c.rs
rustfmt.nightly.toml
src/builder.rs
src/interface/mod.rs
src/interface/spi.rs
src/lib.rs
src/mode/displaymode.rs
src/mode/graphics.rs
src/mode/mod.rs
src/mode/raw.rs
src/mode/terminal.rs
src/prelude.rs
src/properties.rs
src/test_helpers.rs

Upgrades to e-g 0.6.0-alpha.3 and fixes examples/doc examples.

Upgrade embedded-graphics to 0.6.0-alpha.3

---

CHANGELOG.md
Cargo.toml

Upgrade to embedded-graphics 0.6.0

---

src/builder.rs
src/displaysize.rs
src/mode/terminal.rs

Fix some more clippy lints

---

Cargo.toml
examples/rtfm_dvd.rs
src/builder.rs
src/command.rs
src/mode/displaymode.rs
src/mode/graphics.rs
src/mode/raw.rs
src/mode/terminal.rs
src/properties.rs
src/test_helpers.rs

Adapt to new display-interface API which allows for dynamic data widths.

Use new display-interface v0.3

---

CHANGELOG.md
Cargo.toml

Submitted this separately to make the changelog more tidy.

Use v0.4 display-interface

---

CHANGELOG.md
examples/rtfm_brightness.rs
src/brightness.rs
src/command.rs
src/lib.rs
src/mode/graphics.rs
src/mode/terminal.rs
src/prelude.rs
src/properties.rs

Some open questions that I still have:
- Should there be an option for custom brightness levels? Adjusting the precharge period can make the screen go darker than default, but the results are not straight forward
- Should there be an additional method per display mode? I personally prefer the `change_property` with a closure, because it allows for the same (and more) functionality without implementing a bunch of forwarder methods. Or maybe it is overly generic in the current form.
So for now, this is only a draft.

Brightness change

---

Cargo.toml
examples/rtic_brightness.rs
examples/rtic_dvd.rs

Update RTIC and replace mentions of the old deprecated name

---

CHANGELOG.md
src/mode/terminal.rs

- ~~Check that you've added documentation to any new methods~~
- ~~Add or modify an example if there are changes to the public API~~
Fix display rotation in terminal mode, referencing #145.
Only tested with a 96x16 display module.

Fix display rotation in terminal mode

---

CHANGELOG.md
src/lib.rs

Added a function for mirroring/flipping the display. Not that elegant, but seems to be working (tested on one display so far). Let me know if this is acceptable.

Add mirror (vertical flip) option

---

src/mode/terminal.rs

While coherence rules don't allow us to implement `From<Result<...>>` we can do `From<OneError> for OtherError` and let the `?` operator handle the conversion.
I don't believe this needs a changelog entry but let me know if it does.

Simplify terminal mode error handling

---

CHANGELOG.md
src/command.rs
src/rotation.rs
src/size.rs

Looking at some of the stuff that my spell checker found, it might be set to US Enligsh, so I hope I didn't unfix something that was correct in real English.

Fix spelling

---

CHANGELOG.md
src/brightness.rs

Make Brightness::custom public

---

CHANGELOG.md
src/command.rs
src/mode/terminal.rs

Fix rotated terminal panic/behaviour

---

examples/text_i2c.rs

Code comments are outdated, update the font size description.

chore: update comment

---

src/command.rs
src/i2c_interface.rs
src/lib.rs
src/mode/buffered_graphics.rs
src/mode/terminal.rs

Just noticed the project is set to deny_warnings but there are clippy warnings. Let me know what you think!

Clippy fixes
